# Bandit configuration file
# Skip certain tests that are false positives for our calculator

skips:
  - 'B101'  # assert_used - we need asserts in tests
  - 'B102'  # exec_used - we don't use exec
  - 'B103'  # set_bad_file_permissions - not applicable
  - 'B104'  # hardcoded_bind_all_interfaces - not applicable
  - 'B105'  # hardcoded_password_string - not applicable
  - 'B106'  # hardcoded_password_funcarg - not applicable
  - 'B107'  # hardcoded_password_default - not applicable
  - 'B108'  # hardcoded_tmp_directory - not applicable
  - 'B301'  # pickle - we don't use pickle
  - 'B302'  # marshal - we don't use marshal
  - 'B303'  # md5 - we don't use weak hashes
  - 'B304'  # ciphers_without_iv - not applicable
  - 'B305'  # blacklist - not applicable
  - 'B306'  # mktemp_q - not applicable
  - 'B307'  # flask_debug_true - not applicable
  - 'B308'  # mark_safe - not applicable
  - 'B309'  # https_connection - not applicable
  - 'B310'  # urllib_urlopen - not applicable
  - 'B311'  # random - we use random only for tests
  - 'B312'  # telnet_connection - not applicable
  - 'B313'  # xml_bad_cElementTree - not applicable
  - 'B314'  # xml_bad_ElementTree - not applicable
  - 'B315'  # xml_bad_expatbuilder - not applicable
  - 'B316'  # xml_bad_expatreader - not applicable
  - 'B317'  # xml_bad_sax - not applicable
  - 'B318'  # xml_bad_minidom - not applicable
  - 'B319'  # xml_bad_pulldom - not applicable
  - 'B320'  # xml_bad_etree - not applicable
  - 'B321'  # ftplib - not applicable
  - 'B322'  # input - we don't use input() in production
  - 'B323'  # unverified_context - not applicable
  - 'B324'  # hashlib_new_insecure_functions - not applicable
  - 'B325'  # tempnam - not applicable
  - 'B326'  # mkstemp - not applicable
  - 'B327'  # mktemp - not applicable
  - 'B401'  # import_telnetlib - not applicable
  - 'B402'  # import_ftplib - not applicable
  - 'B403'  # import_pickle - not applicable
  - 'B404'  # import_subprocess - not applicable
  - 'B405'  # import_xml_etree - not applicable
  - 'B406'  # import_xml_sax - not applicable
  - 'B407'  # import_xml_expat - not applicable
  - 'B408'  # import_xml_minidom - not applicable
  - 'B409'  # import_xml_pulldom - not applicable
  - 'B410'  # import_lxml - not applicable
  - 'B411'  # import_xmlrpclib - not applicable
  - 'B412'  # import_httpoxy - not applicable
  - 'B413'  # import_pycrypto - not applicable
  - 'B414'  # import_pty - not applicable
  - 'B415'  # import_posix_ipc - not applicable
  - 'B416'  # import_flask_restx - not applicable
  - 'B417'  # import_http_client - not applicable
  - 'B418'  # import_urllib_request - not applicable
  - 'B419'  # import_urllib - not applicable
  - 'B420'  # import_urllib2 - not applicable
  - 'B421'  # import_httplib - not applicable
  - 'B422'  # import_requests - not applicable
  - 'B423'  # import_urllib3 - not applicable
